/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.records;


import models.talentDB.tables.Follower;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "Follower", schema = "talent")
public class FollowerRecord extends UpdatableRecordImpl<FollowerRecord> implements Record4<Integer, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = 1624690736;

    /**
     * Create a detached FollowerRecord
     */
    public FollowerRecord() {
        super(Follower.FOLLOWER);
    }

    /**
     * Create a detached, initialised FollowerRecord
     */
    public FollowerRecord(Integer followerId, Timestamp date, Integer followed, Integer follower) {
        super(Follower.FOLLOWER);

        set(0, followerId);
        set(1, date);
        set(2, followed);
        set(3, follower);
    }

    /**
     * Getter for <code>talent.Follower.Follower_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Follower_ID", unique = true, nullable = false, precision = 10)
    @NotNull
    public Integer getFollowerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>talent.Follower.Follower_ID</code>.
     */
    public void setFollowerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>talent.Follower.Date</code>.
     */
    @Column(name = "Date", nullable = false)
    public Timestamp getDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>talent.Follower.Date</code>.
     */
    public void setDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>talent.Follower.Followed</code>.
     */
    @Column(name = "Followed", nullable = false, precision = 10)
    @NotNull
    public Integer getFollowed() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>talent.Follower.Followed</code>.
     */
    public void setFollowed(Integer value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>talent.Follower.Follower</code>.
     */
    @Column(name = "Follower", nullable = false, precision = 10)
    @NotNull
    public Integer getFollower() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>talent.Follower.Follower</code>.
     */
    public void setFollower(Integer value) {
        set(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Follower.FOLLOWER.FOLLOWER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Follower.FOLLOWER.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Follower.FOLLOWER.FOLLOWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Follower.FOLLOWER.FOLLOWER_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFollowerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFollowed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFollower();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord value1(Integer value) {
        setFollowerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord value2(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord value3(Integer value) {
        setFollowed(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord value4(Integer value) {
        setFollower(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
