/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.records;


import models.talentDB.tables.Rate;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "Rate", schema = "talent")
public class RateRecord extends UpdatableRecordImpl<RateRecord> implements Record5<Integer, Integer, Double, Integer, Timestamp> {

    private static final long serialVersionUID = 1487412114;

    /**
     * Create a detached RateRecord
     */
    public RateRecord() {
        super(Rate.RATE);
    }

    /**
     * Create a detached, initialised RateRecord
     */
    public RateRecord(Integer rateId, Integer postId, Double rating, Integer userId, Timestamp date) {
        super(Rate.RATE);

        set(0, rateId);
        set(1, postId);
        set(2, rating);
        set(3, userId);
        set(4, date);
    }

    /**
     * Getter for <code>talent.Rate.Rate_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Rate_ID", unique = true, nullable = false, precision = 10)
    @NotNull
    public Integer getRateId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>talent.Rate.Rate_ID</code>.
     */
    public void setRateId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>talent.Rate.Post_ID</code>.
     */
    @Column(name = "Post_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getPostId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>talent.Rate.Post_ID</code>.
     */
    public void setPostId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>talent.Rate.Rating</code>.
     */
    @Column(name = "Rating", nullable = false, precision = 12)
    @NotNull
    public Double getRating() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>talent.Rate.Rating</code>.
     */
    public void setRating(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>talent.Rate.User_ID</code>.
     */
    @Column(name = "User_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>talent.Rate.User_ID</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>talent.Rate.Date</code>.
     */
    @Column(name = "Date", nullable = false)
    public Timestamp getDate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>talent.Rate.Date</code>.
     */
    public void setDate(Timestamp value) {
        set(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Double, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Double, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Rate.RATE.RATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Rate.RATE.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Rate.RATE.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Rate.RATE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Rate.RATE.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RateRecord value1(Integer value) {
        setRateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RateRecord value2(Integer value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RateRecord value3(Double value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RateRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RateRecord value5(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RateRecord values(Integer value1, Integer value2, Double value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
