/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.records;


import java.sql.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import models.talentDB.tables.TopRated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "Top Rated", schema = "talent")
public class TopRatedRecord extends UpdatableRecordImpl<TopRatedRecord> implements Record5<Integer, Integer, Date, Date, Double> {

    private static final long serialVersionUID = -678699113;

    /**
     * Setter for <code>talent.Top Rated.User_ID</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>talent.Top Rated.User_ID</code>.
     */
    @Id
    @Column(name = "User_ID", unique = true, nullable = false, precision = 10)
    @NotNull
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>talent.Top Rated.Category_ID</code>.
     */
    public void setCategoryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>talent.Top Rated.Category_ID</code>.
     */
    @Column(name = "Category_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getCategoryId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>talent.Top Rated.Start_Date</code>.
     */
    public void setStartDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>talent.Top Rated.Start_Date</code>.
     */
    @Column(name = "Start_Date", nullable = false)
    @NotNull
    public Date getStartDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>talent.Top Rated.End_Date</code>.
     */
    public void setEndDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>talent.Top Rated.End_Date</code>.
     */
    @Column(name = "End_Date")
    public Date getEndDate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>talent.Top Rated.Category_Rating</code>.
     */
    public void setCategoryRating(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>talent.Top Rated.Category_Rating</code>.
     */
    @Column(name = "Category_Rating", nullable = false, precision = 12)
    @NotNull
    public Double getCategoryRating() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Date, Date, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Date, Date, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TopRated.TOP_RATED.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TopRated.TOP_RATED.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return TopRated.TOP_RATED.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return TopRated.TOP_RATED.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return TopRated.TOP_RATED.CATEGORY_RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getCategoryRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopRatedRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopRatedRecord value2(Integer value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopRatedRecord value3(Date value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopRatedRecord value4(Date value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopRatedRecord value5(Double value) {
        setCategoryRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopRatedRecord values(Integer value1, Integer value2, Date value3, Date value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopRatedRecord
     */
    public TopRatedRecord() {
        super(TopRated.TOP_RATED);
    }

    /**
     * Create a detached, initialised TopRatedRecord
     */
    public TopRatedRecord(Integer userId, Integer categoryId, Date startDate, Date endDate, Double categoryRating) {
        super(TopRated.TOP_RATED);

        set(0, userId);
        set(1, categoryId);
        set(2, startDate);
        set(3, endDate);
        set(4, categoryRating);
    }
}
