/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import models.talentDB.tables.Category;
import models.talentDB.tables.records.CategoryRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CategoryDao extends DAOImpl<CategoryRecord, models.talentDB.tables.pojos.Category, Integer> {

    /**
     * Create a new CategoryDao without any configuration
     */
    public CategoryDao() {
        super(Category.CATEGORY, models.talentDB.tables.pojos.Category.class);
    }

    /**
     * Create a new CategoryDao with an attached configuration
     */
    public CategoryDao(Configuration configuration) {
        super(Category.CATEGORY, models.talentDB.tables.pojos.Category.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.talentDB.tables.pojos.Category object) {
        return object.getCategoryId();
    }

    /**
     * Fetch records that have <code>Category_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Category> fetchByCategoryId(Integer... values) {
        return fetch(Category.CATEGORY.CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Category_ID = value</code>
     */
    public models.talentDB.tables.pojos.Category fetchOneByCategoryId(Integer value) {
        return fetchOne(Category.CATEGORY.CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>Name IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Category> fetchByName(String... values) {
        return fetch(Category.CATEGORY.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>Name = value</code>
     */
    public models.talentDB.tables.pojos.Category fetchOneByName(String value) {
        return fetchOne(Category.CATEGORY.NAME, value);
    }

    /**
     * Fetch records that have <code>Number_Of_Posts IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Category> fetchByNumberOfPosts(Integer... values) {
        return fetch(Category.CATEGORY.NUMBER_OF_POSTS, values);
    }
}
