/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import models.talentDB.tables.Comment;
import models.talentDB.tables.records.CommentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentDao extends DAOImpl<CommentRecord, models.talentDB.tables.pojos.Comment, Integer> {

    /**
     * Create a new CommentDao without any configuration
     */
    public CommentDao() {
        super(Comment.COMMENT, models.talentDB.tables.pojos.Comment.class);
    }

    /**
     * Create a new CommentDao with an attached configuration
     */
    public CommentDao(Configuration configuration) {
        super(Comment.COMMENT, models.talentDB.tables.pojos.Comment.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.talentDB.tables.pojos.Comment object) {
        return object.getNotificationId();
    }

    /**
     * Fetch records that have <code>Notification_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Comment> fetchByNotificationId(Integer... values) {
        return fetch(Comment.COMMENT.NOTIFICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Notification_ID = value</code>
     */
    public models.talentDB.tables.pojos.Comment fetchOneByNotificationId(Integer value) {
        return fetchOne(Comment.COMMENT.NOTIFICATION_ID, value);
    }

    /**
     * Fetch records that have <code>Post_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Comment> fetchByPostId(Integer... values) {
        return fetch(Comment.COMMENT.POST_ID, values);
    }

    /**
     * Fetch records that have <code>Text IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Comment> fetchByText(String... values) {
        return fetch(Comment.COMMENT.TEXT, values);
    }
}
