/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import models.talentDB.tables.Follower;
import models.talentDB.tables.records.FollowerRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FollowerDao extends DAOImpl<FollowerRecord, models.talentDB.tables.pojos.Follower, Integer> {

    /**
     * Create a new FollowerDao without any configuration
     */
    public FollowerDao() {
        super(Follower.FOLLOWER, models.talentDB.tables.pojos.Follower.class);
    }

    /**
     * Create a new FollowerDao with an attached configuration
     */
    public FollowerDao(Configuration configuration) {
        super(Follower.FOLLOWER, models.talentDB.tables.pojos.Follower.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.talentDB.tables.pojos.Follower object) {
        return object.getFollowerId();
    }

    /**
     * Fetch records that have <code>Follower_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Follower> fetchByFollowerId(Integer... values) {
        return fetch(Follower.FOLLOWER.FOLLOWER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Follower_ID = value</code>
     */
    public models.talentDB.tables.pojos.Follower fetchOneByFollowerId(Integer value) {
        return fetchOne(Follower.FOLLOWER.FOLLOWER_ID, value);
    }

    /**
     * Fetch records that have <code>Date IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Follower> fetchByDate(Timestamp... values) {
        return fetch(Follower.FOLLOWER.DATE, values);
    }

    /**
     * Fetch records that have <code>Followed IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Follower> fetchByFollowed(Integer... values) {
        return fetch(Follower.FOLLOWER.FOLLOWED, values);
    }

    /**
     * Fetch records that have <code>Follower IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Follower> fetchByFollower(Integer... values) {
        return fetch(Follower.FOLLOWER.FOLLOWER_, values);
    }
}
