/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import models.talentDB.tables.Follower;
import models.talentDB.tables.records.FollowerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FollowerDao extends DAOImpl<FollowerRecord, models.talentDB.tables.pojos.Follower, Integer> {

    /**
     * Create a new FollowerDao without any configuration
     */
    public FollowerDao() {
        super(Follower.FOLLOWER, models.talentDB.tables.pojos.Follower.class);
    }

    /**
     * Create a new FollowerDao with an attached configuration
     */
    public FollowerDao(Configuration configuration) {
        super(Follower.FOLLOWER, models.talentDB.tables.pojos.Follower.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.talentDB.tables.pojos.Follower object) {
        return object.getNotificationId();
    }

    /**
     * Fetch records that have <code>Notification_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Follower> fetchByNotificationId(Integer... values) {
        return fetch(Follower.FOLLOWER.NOTIFICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Notification_ID = value</code>
     */
    public models.talentDB.tables.pojos.Follower fetchOneByNotificationId(Integer value) {
        return fetchOne(Follower.FOLLOWER.NOTIFICATION_ID, value);
    }

    /**
     * Fetch records that have <code>User_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Follower> fetchByUserId(Integer... values) {
        return fetch(Follower.FOLLOWER.USER_ID, values);
    }
}
