/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import models.talentDB.tables.Like;
import models.talentDB.tables.records.LikeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LikeDao extends DAOImpl<LikeRecord, models.talentDB.tables.pojos.Like, Integer> {

    /**
     * Create a new LikeDao without any configuration
     */
    public LikeDao() {
        super(Like.LIKE, models.talentDB.tables.pojos.Like.class);
    }

    /**
     * Create a new LikeDao with an attached configuration
     */
    public LikeDao(Configuration configuration) {
        super(Like.LIKE, models.talentDB.tables.pojos.Like.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.talentDB.tables.pojos.Like object) {
        return object.getNotificationId();
    }

    /**
     * Fetch records that have <code>Notification_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Like> fetchByNotificationId(Integer... values) {
        return fetch(Like.LIKE.NOTIFICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Notification_ID = value</code>
     */
    public models.talentDB.tables.pojos.Like fetchOneByNotificationId(Integer value) {
        return fetchOne(Like.LIKE.NOTIFICATION_ID, value);
    }

    /**
     * Fetch records that have <code>Post_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Like> fetchByPostId(Integer... values) {
        return fetch(Like.LIKE.POST_ID, values);
    }
}
