/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import models.talentDB.tables.PostTag;
import models.talentDB.tables.records.PostTagRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostTagDao extends DAOImpl<PostTagRecord, models.talentDB.tables.pojos.PostTag, Record2<Integer, Integer>> {

    /**
     * Create a new PostTagDao without any configuration
     */
    public PostTagDao() {
        super(PostTag.POST_TAG, models.talentDB.tables.pojos.PostTag.class);
    }

    /**
     * Create a new PostTagDao with an attached configuration
     */
    public PostTagDao(Configuration configuration) {
        super(PostTag.POST_TAG, models.talentDB.tables.pojos.PostTag.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(models.talentDB.tables.pojos.PostTag object) {
        return compositeKeyRecord(object.getTagId(), object.getPostId());
    }

    /**
     * Fetch records that have <code>Tag_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.PostTag> fetchByTagId(Integer... values) {
        return fetch(PostTag.POST_TAG.TAG_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Tag_ID = value</code>
     */
    public models.talentDB.tables.pojos.PostTag fetchOneByTagId(Integer value) {
        return fetchOne(PostTag.POST_TAG.TAG_ID, value);
    }

    /**
     * Fetch records that have <code>Post_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.PostTag> fetchByPostId(Integer... values) {
        return fetch(PostTag.POST_TAG.POST_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Post_ID = value</code>
     */
    public models.talentDB.tables.pojos.PostTag fetchOneByPostId(Integer value) {
        return fetchOne(PostTag.POST_TAG.POST_ID, value);
    }
}
