/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import models.talentDB.tables.Rate;
import models.talentDB.tables.records.RateRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RateDao extends DAOImpl<RateRecord, models.talentDB.tables.pojos.Rate, Integer> {

    /**
     * Create a new RateDao without any configuration
     */
    public RateDao() {
        super(Rate.RATE, models.talentDB.tables.pojos.Rate.class);
    }

    /**
     * Create a new RateDao with an attached configuration
     */
    public RateDao(Configuration configuration) {
        super(Rate.RATE, models.talentDB.tables.pojos.Rate.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.talentDB.tables.pojos.Rate object) {
        return object.getNotificationId();
    }

    /**
     * Fetch records that have <code>Notification_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Rate> fetchByNotificationId(Integer... values) {
        return fetch(Rate.RATE.NOTIFICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Notification_ID = value</code>
     */
    public models.talentDB.tables.pojos.Rate fetchOneByNotificationId(Integer value) {
        return fetchOne(Rate.RATE.NOTIFICATION_ID, value);
    }

    /**
     * Fetch records that have <code>Post_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Rate> fetchByPostId(Integer... values) {
        return fetch(Rate.RATE.POST_ID, values);
    }

    /**
     * Fetch records that have <code>Rating IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.Rate> fetchByRating(Double... values) {
        return fetch(Rate.RATE.RATING, values);
    }
}
