/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.daos;


import models.talentDB.tables.TopRated;
import models.talentDB.tables.records.TopRatedRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TopRatedDao extends DAOImpl<TopRatedRecord, models.talentDB.tables.pojos.TopRated, Integer> {

    /**
     * Create a new TopRatedDao without any configuration
     */
    public TopRatedDao() {
        super(TopRated.TOP_RATED, models.talentDB.tables.pojos.TopRated.class);
    }

    /**
     * Create a new TopRatedDao with an attached configuration
     */
    public TopRatedDao(Configuration configuration) {
        super(TopRated.TOP_RATED, models.talentDB.tables.pojos.TopRated.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.talentDB.tables.pojos.TopRated object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>User_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.TopRated> fetchByUserId(Integer... values) {
        return fetch(TopRated.TOP_RATED.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>User_ID = value</code>
     */
    public models.talentDB.tables.pojos.TopRated fetchOneByUserId(Integer value) {
        return fetchOne(TopRated.TOP_RATED.USER_ID, value);
    }

    /**
     * Fetch records that have <code>Category_ID IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.TopRated> fetchByCategoryId(Integer... values) {
        return fetch(TopRated.TOP_RATED.CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>Start_Date IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.TopRated> fetchByStartDate(Date... values) {
        return fetch(TopRated.TOP_RATED.START_DATE, values);
    }

    /**
     * Fetch records that have <code>End_Date IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.TopRated> fetchByEndDate(Date... values) {
        return fetch(TopRated.TOP_RATED.END_DATE, values);
    }

    /**
     * Fetch records that have <code>Category_Rating IN (values)</code>
     */
    public List<models.talentDB.tables.pojos.TopRated> fetchByCategoryRating(Double... values) {
        return fetch(TopRated.TOP_RATED.CATEGORY_RATING, values);
    }
}
