/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import models.talentDB.Keys;
import models.talentDB.Talent;
import models.talentDB.tables.records.FollowerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Follower extends TableImpl<FollowerRecord> {

    private static final long serialVersionUID = 1496361517;

    /**
     * The reference instance of <code>talent.Follower</code>
     */
    public static final Follower FOLLOWER = new Follower();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FollowerRecord> getRecordType() {
        return FollowerRecord.class;
    }

    /**
     * The column <code>talent.Follower.Notification_ID</code>.
     */
    public final TableField<FollowerRecord, Integer> NOTIFICATION_ID = createField("Notification_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>talent.Follower.User_ID</code>.
     */
    public final TableField<FollowerRecord, Integer> USER_ID = createField("User_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>talent.Follower</code> table reference
     */
    public Follower() {
        this("Follower", null);
    }

    /**
     * Create an aliased <code>talent.Follower</code> table reference
     */
    public Follower(String alias) {
        this(alias, FOLLOWER);
    }

    private Follower(String alias, Table<FollowerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Follower(String alias, Table<FollowerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talent.TALENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FollowerRecord> getPrimaryKey() {
        return Keys.KEY_FOLLOWER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FollowerRecord>> getKeys() {
        return Arrays.<UniqueKey<FollowerRecord>>asList(Keys.KEY_FOLLOWER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<FollowerRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FollowerRecord, ?>>asList(Keys.FKFOLLOWER973342, Keys.FKFOLLOWER837875);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Follower as(String alias) {
        return new Follower(alias, this);
    }

    /**
     * Rename this table
     */
    public Follower rename(String name) {
        return new Follower(name, null);
    }
}
