/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import models.talentDB.Keys;
import models.talentDB.Talent;
import models.talentDB.tables.records.LikeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Like extends TableImpl<LikeRecord> {

    private static final long serialVersionUID = -41392903;

    /**
     * The reference instance of <code>talent.Like</code>
     */
    public static final Like LIKE = new Like();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LikeRecord> getRecordType() {
        return LikeRecord.class;
    }

    /**
     * The column <code>talent.Like.Notification_ID</code>.
     */
    public final TableField<LikeRecord, Integer> NOTIFICATION_ID = createField("Notification_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>talent.Like.Post_ID</code>.
     */
    public final TableField<LikeRecord, Integer> POST_ID = createField("Post_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>talent.Like</code> table reference
     */
    public Like() {
        this("Like", null);
    }

    /**
     * Create an aliased <code>talent.Like</code> table reference
     */
    public Like(String alias) {
        this(alias, LIKE);
    }

    private Like(String alias, Table<LikeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Like(String alias, Table<LikeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talent.TALENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LikeRecord> getPrimaryKey() {
        return Keys.KEY_LIKE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LikeRecord>> getKeys() {
        return Arrays.<UniqueKey<LikeRecord>>asList(Keys.KEY_LIKE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<LikeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<LikeRecord, ?>>asList(Keys.FKLIKE895787, Keys.FKLIKE225956);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Like as(String alias) {
        return new Like(alias, this);
    }

    /**
     * Rename this table
     */
    public Like rename(String name) {
        return new Like(name, null);
    }
}
