/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables;


import models.talentDB.Keys;
import models.talentDB.Talent;
import models.talentDB.tables.records.LikeRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Like extends TableImpl<LikeRecord> {

    /**
     * The reference instance of <code>talent.Like</code>
     */
    public static final Like LIKE = new Like();
    private static final long serialVersionUID = -1670577728;
    /**
     * The column <code>talent.Like.Like_ID</code>.
     */
    public final TableField<LikeRecord, Integer> LIKE_ID = createField("Like_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>talent.Like.Post_ID</code>.
     */
    public final TableField<LikeRecord, Integer> POST_ID = createField("Post_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>talent.Like.User_ID</code>.
     */
    public final TableField<LikeRecord, Integer> USER_ID = createField("User_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>talent.Like.Date</code>.
     */
    public final TableField<LikeRecord, Timestamp> DATE = createField("Date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>talent.Like</code> table reference
     */
    public Like() {
        this("Like", null);
    }

    /**
     * Create an aliased <code>talent.Like</code> table reference
     */
    public Like(String alias) {
        this(alias, LIKE);
    }

    private Like(String alias, Table<LikeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Like(String alias, Table<LikeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LikeRecord> getRecordType() {
        return LikeRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talent.TALENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LikeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_LIKE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LikeRecord> getPrimaryKey() {
        return Keys.KEY_LIKE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LikeRecord>> getKeys() {
        return Arrays.<UniqueKey<LikeRecord>>asList(Keys.KEY_LIKE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Like as(String alias) {
        return new Like(alias, this);
    }

    /**
     * Rename this table
     */
    public Like rename(String name) {
        return new Like(name, null);
    }
}
