/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables;


import models.talentDB.Keys;
import models.talentDB.Talent;
import models.talentDB.tables.records.PostTagRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PostTag extends TableImpl<PostTagRecord> {

    /**
     * The reference instance of <code>talent.Post Tag</code>
     */
    public static final PostTag POST_TAG = new PostTag();
    private static final long serialVersionUID = -1358816554;
    /**
     * The column <code>talent.Post Tag.Tag_ID</code>.
     */
    public final TableField<PostTagRecord, Integer> TAG_ID = createField("Tag_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>talent.Post Tag.Post_ID</code>.
     */
    public final TableField<PostTagRecord, Integer> POST_ID = createField("Post_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>talent.Post Tag</code> table reference
     */
    public PostTag() {
        this("Post Tag", null);
    }

    /**
     * Create an aliased <code>talent.Post Tag</code> table reference
     */
    public PostTag(String alias) {
        this(alias, POST_TAG);
    }

    private PostTag(String alias, Table<PostTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostTag(String alias, Table<PostTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostTagRecord> getRecordType() {
        return PostTagRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talent.TALENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostTagRecord> getPrimaryKey() {
        return Keys.KEY_POST_TAG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostTagRecord>> getKeys() {
        return Arrays.<UniqueKey<PostTagRecord>>asList(Keys.KEY_POST_TAG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTag as(String alias) {
        return new PostTag(alias, this);
    }

    /**
     * Rename this table
     */
    public PostTag rename(String name) {
        return new PostTag(name, null);
    }
}
