/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import models.talentDB.Keys;
import models.talentDB.Talent;
import models.talentDB.tables.records.PostTagRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostTag extends TableImpl<PostTagRecord> {

    private static final long serialVersionUID = -2116524036;

    /**
     * The reference instance of <code>talent.Post Tag</code>
     */
    public static final PostTag POST_TAG = new PostTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostTagRecord> getRecordType() {
        return PostTagRecord.class;
    }

    /**
     * The column <code>talent.Post Tag.Tag_ID</code>.
     */
    public final TableField<PostTagRecord, Integer> TAG_ID = createField("Tag_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>talent.Post Tag.Post_ID</code>.
     */
    public final TableField<PostTagRecord, Integer> POST_ID = createField("Post_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>talent.Post Tag</code> table reference
     */
    public PostTag() {
        this("Post Tag", null);
    }

    /**
     * Create an aliased <code>talent.Post Tag</code> table reference
     */
    public PostTag(String alias) {
        this(alias, POST_TAG);
    }

    private PostTag(String alias, Table<PostTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostTag(String alias, Table<PostTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talent.TALENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostTagRecord> getPrimaryKey() {
        return Keys.KEY_POST_TAG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostTagRecord>> getKeys() {
        return Arrays.<UniqueKey<PostTagRecord>>asList(Keys.KEY_POST_TAG_PRIMARY, Keys.KEY_POST_TAG_TAG_ID, Keys.KEY_POST_TAG_POST_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PostTagRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PostTagRecord, ?>>asList(Keys.FKPOST_TAG387460, Keys.FKPOST_TAG508815);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTag as(String alias) {
        return new PostTag(alias, this);
    }

    /**
     * Rename this table
     */
    public PostTag rename(String name) {
        return new PostTag(name, null);
    }
}
