/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables;


import models.talentDB.Keys;
import models.talentDB.Talent;
import models.talentDB.tables.records.TagRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tag extends TableImpl<TagRecord> {

    /**
     * The reference instance of <code>talent.Tag</code>
     */
    public static final Tag TAG = new Tag();
    private static final long serialVersionUID = 1485294543;
    /**
     * The column <code>talent.Tag.Tag_ID</code>.
     */
    public final TableField<TagRecord, Integer> TAG_ID = createField("Tag_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>talent.Tag.Name</code>.
     */
    public final TableField<TagRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>talent.Tag</code> table reference
     */
    public Tag() {
        this("Tag", null);
    }

    /**
     * Create an aliased <code>talent.Tag</code> table reference
     */
    public Tag(String alias) {
        this(alias, TAG);
    }

    private Tag(String alias, Table<TagRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tag(String alias, Table<TagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagRecord> getRecordType() {
        return TagRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talent.TALENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TagRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TagRecord> getPrimaryKey() {
        return Keys.KEY_TAG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TagRecord>> getKeys() {
        return Arrays.<UniqueKey<TagRecord>>asList(Keys.KEY_TAG_PRIMARY, Keys.KEY_TAG_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tag as(String alias) {
        return new Tag(alias, this);
    }

    /**
     * Rename this table
     */
    public Tag rename(String name) {
        return new Tag(name, null);
    }
}
