/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables;


import models.talentDB.Keys;
import models.talentDB.Talent;
import models.talentDB.tables.records.UserRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User extends TableImpl<UserRecord> {

    /**
     * The reference instance of <code>talent.User</code>
     */
    public static final User USER = new User();
    private static final long serialVersionUID = -1657931715;
    /**
     * The column <code>talent.User.User_ID</code>.
     */
    public final TableField<UserRecord, Integer> USER_ID = createField("User_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>talent.User.Nickname</code>.
     */
    public final TableField<UserRecord, String> NICKNAME = createField("Nickname", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");
    /**
     * The column <code>talent.User.Username</code>.
     */
    public final TableField<UserRecord, String> USERNAME = createField("Username", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");
    /**
     * The column <code>talent.User.Password</code>.
     */
    public final TableField<UserRecord, String> PASSWORD = createField("Password", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");
    /**
     * The column <code>talent.User.Email</code>.
     */
    public final TableField<UserRecord, String> EMAIL = createField("Email", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");
    /**
     * The column <code>talent.User.Date_Of_Birth</code>.
     */
    public final TableField<UserRecord, Date> DATE_OF_BIRTH = createField("Date_Of_Birth", org.jooq.impl.SQLDataType.DATE, this, "");
    /**
     * The column <code>talent.User.Bio</code>.
     */
    public final TableField<UserRecord, String> BIO = createField("Bio", org.jooq.impl.SQLDataType.CHAR.length(255), this, "");
    /**
     * The column <code>talent.User.Profile_Picture</code>.
     */
    public final TableField<UserRecord, String> PROFILE_PICTURE = createField("Profile_Picture", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");
    /**
     * The column <code>talent.User.Facebook</code>.
     */
    public final TableField<UserRecord, String> FACEBOOK = createField("Facebook", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");
    /**
     * The column <code>talent.User.Youtube</code>.
     */
    public final TableField<UserRecord, String> YOUTUBE = createField("Youtube", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");
    /**
     * The column <code>talent.User.Profile_Link</code>.
     */
    public final TableField<UserRecord, String> PROFILE_LINK = createField("Profile_Link", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");
    /**
     * The column <code>talent.User.lat</code>.
     */
    public final TableField<UserRecord, Double> LAT = createField("lat", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>talent.User.lang</code>.
     */
    public final TableField<UserRecord, Double> LANG = createField("lang", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>talent.User</code> table reference
     */
    public User() {
        this("User", null);
    }

    /**
     * Create an aliased <code>talent.User</code> table reference
     */
    public User(String alias) {
        this(alias, USER);
    }

    private User(String alias, Table<UserRecord> aliased) {
        this(alias, aliased, null);
    }

    private User(String alias, Table<UserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRecord> getRecordType() {
        return UserRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talent.TALENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserRecord> getPrimaryKey() {
        return Keys.KEY_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserRecord>> getKeys() {
        return Arrays.<UniqueKey<UserRecord>>asList(Keys.KEY_USER_PRIMARY, Keys.KEY_USER_USERNAME, Keys.KEY_USER_EMAIL, Keys.KEY_USER_PROFILE_LINK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User as(String alias) {
        return new User(alias, this);
    }

    /**
     * Rename this table
     */
    public User rename(String name) {
        return new User(name, null);
    }
}
