/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.pojos;


import models.RESTHelper;
import play.data.validation.ValidationError;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "Like", schema = "talent")
public class Like implements Serializable {

    private static final long serialVersionUID = -1632479216;

    private Integer likeId;
    private Integer postId;
    private Integer userId;
    private Timestamp date;

    public Like() {
    }

    public Like(Like value) {
        this.likeId = value.likeId;
        this.postId = value.postId;
        this.userId = value.userId;
        this.date = value.date;
    }

    public Like(
            Integer likeId,
            Integer postId,
            Integer userId,
            Timestamp date
    ) {
        this.likeId = likeId;
        this.postId = postId;
        this.userId = userId;
        this.date = date;
    }

    public List<ValidationError> validate() throws SQLException {
        List<ValidationError> errors = new ArrayList<ValidationError>();
        RESTHelper restHelper = new RESTHelper();

        if (postId == null) {
            errors.add(new ValidationError("postId", "postId is requered"));
        } else if (!(restHelper.getWhere("post", "Post_ID", String.valueOf(postId)).size() > 0)) {
            errors.add(new ValidationError("postId", "this postId not found"));
        } else {
            Map<String, String> map = new HashMap<>();
            map.put("Post_ID", String.valueOf(postId));
            map.put("User_ID", String.valueOf(userId));
            List<models.talentDB.tables.pojos.Like> like = restHelper.getWhereCondition("like", new String[]{"AND"}, map);
            if (like.size() > 0) {
                for (int i = 0; i < like.size(); i++) {
                    restHelper.deleteByID("like", String.valueOf(like.get(i).likeId));
                }
                errors.add(new ValidationError("postId", "you liked this post before"));

            }
        }


        return errors.isEmpty() ? null : errors;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Like_ID", unique = true, nullable = false, precision = 10)
    public Integer getLikeId() {
        return this.likeId;
    }

    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    @Column(name = "Post_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getPostId() {
        return this.postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    @Column(name = "User_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "Date", nullable = false)
    public Timestamp getDate() {
        return this.date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Like (");

        sb.append(likeId);
        sb.append(", ").append(postId);
        sb.append(", ").append(userId);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
}
