/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "Notification", schema = "talent")
public class Notification implements Serializable {

    private static final long serialVersionUID = 39031851;

    private Integer notificationId;
    private Integer userId;
    private Timestamp date;
    private String type;

    public Notification() {
    }

    public Notification(Notification value) {
        this.notificationId = value.notificationId;
        this.userId = value.userId;
        this.date = value.date;
        this.type = value.type;
    }

    public Notification(
            Integer notificationId,
            Integer userId,
            Timestamp date,
            String type
    ) {
        this.notificationId = notificationId;
        this.userId = userId;
        this.date = date;
        this.type = type;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Notification_ID", unique = true, nullable = false, precision = 10)
    public Integer getNotificationId() {
        return this.notificationId;
    }

    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }

    @Column(name = "User_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "Date", nullable = false)
    public Timestamp getDate() {
        return this.date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    @Column(name = "Type", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notification (");

        sb.append(notificationId);
        sb.append(", ").append(userId);
        sb.append(", ").append(date);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
