/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "Tag", schema = "talent")
public class Tag implements Serializable {

    private static final long serialVersionUID = 22097267;

    private Integer tagId;
    private String name;

    public Tag() {
    }

    public Tag(Tag value) {
        this.tagId = value.tagId;
        this.name = value.name;
    }

    public Tag(
            Integer tagId,
            String name
    ) {
        this.tagId = tagId;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Tag_ID", unique = true, nullable = false, precision = 10)
    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Column(name = "Name", unique = true, nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(tagId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
