/**
 * This class is generated by jOOQ
 */
package models.talentDB.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "Tag", schema = "talent")
public class Tag implements Serializable {

    private static final long serialVersionUID = 861184069;

    private Integer tagId;
    private String  name;
    private Integer numberOfPosts;

    public Tag() {}

    public Tag(Tag value) {
        this.tagId = value.tagId;
        this.name = value.name;
        this.numberOfPosts = value.numberOfPosts;
    }

    public Tag(
        Integer tagId,
        String  name,
        Integer numberOfPosts
    ) {
        this.tagId = tagId;
        this.name = name;
        this.numberOfPosts = numberOfPosts;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Tag_ID", unique = true, nullable = false, precision = 10)
    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Column(name = "Name", unique = true, nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Number_Of_Posts", nullable = false, precision = 10)
    @NotNull
    public Integer getNumberOfPosts() {
        return this.numberOfPosts;
    }

    public void setNumberOfPosts(Integer numberOfPosts) {
        this.numberOfPosts = numberOfPosts;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(tagId);
        sb.append(", ").append(name);
        sb.append(", ").append(numberOfPosts);

        sb.append(")");
        return sb.toString();
    }
}
