/**
 * This class is generated by jOOQ
 */
package models.talentDB;


import javax.annotation.Generated;

import models.talentDB.tables.Category;
import models.talentDB.tables.Comment;
import models.talentDB.tables.Databasechangelog;
import models.talentDB.tables.Databasechangeloglock;
import models.talentDB.tables.Follower;
import models.talentDB.tables.Like;
import models.talentDB.tables.Notification;
import models.talentDB.tables.Post;
import models.talentDB.tables.PostTag;
import models.talentDB.tables.Rate;
import models.talentDB.tables.Tag;
import models.talentDB.tables.TopRated;
import models.talentDB.tables.User;


/**
 * Convenience access to all tables in talent
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>talent.Category</code>.
     */
    public static final Category CATEGORY = models.talentDB.tables.Category.CATEGORY;

    /**
     * The table <code>talent.Comment</code>.
     */
    public static final Comment COMMENT = models.talentDB.tables.Comment.COMMENT;

    /**
     * The table <code>talent.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = models.talentDB.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>talent.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = models.talentDB.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>talent.Follower</code>.
     */
    public static final Follower FOLLOWER = models.talentDB.tables.Follower.FOLLOWER;

    /**
     * The table <code>talent.Like</code>.
     */
    public static final Like LIKE = models.talentDB.tables.Like.LIKE;

    /**
     * The table <code>talent.Notification</code>.
     */
    public static final Notification NOTIFICATION = models.talentDB.tables.Notification.NOTIFICATION;

    /**
     * The table <code>talent.Post</code>.
     */
    public static final Post POST = models.talentDB.tables.Post.POST;

    /**
     * The table <code>talent.Post Tag</code>.
     */
    public static final PostTag POST_TAG = models.talentDB.tables.PostTag.POST_TAG;

    /**
     * The table <code>talent.Rate</code>.
     */
    public static final Rate RATE = models.talentDB.tables.Rate.RATE;

    /**
     * The table <code>talent.Tag</code>.
     */
    public static final Tag TAG = models.talentDB.tables.Tag.TAG;

    /**
     * The table <code>talent.Top Rated</code>.
     */
    public static final TopRated TOP_RATED = models.talentDB.tables.TopRated.TOP_RATED;

    /**
     * The table <code>talent.User</code>.
     */
    public static final User USER = models.talentDB.tables.User.USER;
}
