/**
 * This class is generated by jOOQ
 */
package models.talentDB;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import models.talentDB.tables.Category;
import models.talentDB.tables.Comment;
import models.talentDB.tables.Databasechangelog;
import models.talentDB.tables.Databasechangeloglock;
import models.talentDB.tables.Follower;
import models.talentDB.tables.Like;
import models.talentDB.tables.Notification;
import models.talentDB.tables.Post;
import models.talentDB.tables.PostTag;
import models.talentDB.tables.Rate;
import models.talentDB.tables.Tag;
import models.talentDB.tables.TopRated;
import models.talentDB.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Talent extends SchemaImpl {

    private static final long serialVersionUID = -1155881132;

    /**
     * The reference instance of <code>talent</code>
     */
    public static final Talent TALENT = new Talent();

    /**
     * The table <code>talent.Category</code>.
     */
    public final Category CATEGORY = models.talentDB.tables.Category.CATEGORY;

    /**
     * The table <code>talent.Comment</code>.
     */
    public final Comment COMMENT = models.talentDB.tables.Comment.COMMENT;

    /**
     * The table <code>talent.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = models.talentDB.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>talent.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = models.talentDB.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>talent.Follower</code>.
     */
    public final Follower FOLLOWER = models.talentDB.tables.Follower.FOLLOWER;

    /**
     * The table <code>talent.Like</code>.
     */
    public final Like LIKE = models.talentDB.tables.Like.LIKE;

    /**
     * The table <code>talent.Notification</code>.
     */
    public final Notification NOTIFICATION = models.talentDB.tables.Notification.NOTIFICATION;

    /**
     * The table <code>talent.Post</code>.
     */
    public final Post POST = models.talentDB.tables.Post.POST;

    /**
     * The table <code>talent.Post Tag</code>.
     */
    public final PostTag POST_TAG = models.talentDB.tables.PostTag.POST_TAG;

    /**
     * The table <code>talent.Rate</code>.
     */
    public final Rate RATE = models.talentDB.tables.Rate.RATE;

    /**
     * The table <code>talent.Tag</code>.
     */
    public final Tag TAG = models.talentDB.tables.Tag.TAG;

    /**
     * The table <code>talent.Top Rated</code>.
     */
    public final TopRated TOP_RATED = models.talentDB.tables.TopRated.TOP_RATED;

    /**
     * The table <code>talent.User</code>.
     */
    public final User USER = models.talentDB.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Talent() {
        super("talent", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Comment.COMMENT,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Follower.FOLLOWER,
            Like.LIKE,
            Notification.NOTIFICATION,
            Post.POST,
            PostTag.POST_TAG,
            Rate.RATE,
            Tag.TAG,
            TopRated.TOP_RATED,
            User.USER);
    }
}
